const Data = {
    productItems: [
        {
            id: 1,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "T-Shirt",
            desc: "Men's White T-shirt",
            category: "",
            price: 1999,
        },
        {
            id: 2,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Shirt",
            desc: "Men's Navy Blue Slim Fit Shirt",
            category: "",
            price: 599,
        },
        {
            id: 3,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Jeans",
            desc: "Men's Blue Washed Jeans",
            category: "",
            price: 1057,
        },
        {
            id: 4,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Sweatshirt",
            desc: "Men's Green Oversized Sweatshirt",
            category: "",
            price: 2000,
        },
        {
            id: 5,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Joggers",
            desc: "Men's Black Joggers",
            category: "",
            price: 1499,
        },
        {
            id: 6,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Hoodies",
            desc: "Sage Green Casual Cotton Hoodies",
            category: "",
            price: 1599,
        },
        {
            id: 7,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Kurta",
            desc: "Olive Night Plus Size Fit Long Kurta",
            category: "",
            price: 800,
        },
        {
            id: 8,
            url: "https://rukminim1.flixcart.com/image/312/312/l0e6kcw0/t-shirt/h/g/d/m-half-triangel-black-one-nb-nicky-boy-original-imagc747apzffz5q.jpeg",
            name: "Sweater",
            desc: "Men's Olive Flat Knits Sweater",
            category: "",
            price: 1000,
        },
    ],
};
export default Data;
